language: node_js
node_js:
    - "node"
    - "7"
    - "8"

before_script:
    - npm install
    - cd client
    - npm install
    - cd ..

script:
    - npm test

after_success:
    - npm run report-codecov
