version: '3'
services:
    gomoku_express:
        image: ptorn/bth-ramverk2:latest

        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/ramverk2
        user: "node"
        working_dir: /home/node/app
        ports:
            - "3000:3000"
        links:
            - mongodb
        command: "npm start"

    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip 0.0.0.0
