version: "3"
services:
    ramverk2_latest:
      image: ptorn/bth-ramverk2:latest
    #   build:
    #     context: .
    #     dockerfile: dockerfiles/Dockerfile_node9
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/client/node_modules
      ports:
        - "8000:3000"
      command: "npm start"

    ramverk2_node9:
      image: ptorn/bth-ramverk2:node9
    #   build:
    #     context: .
    #     dockerfile: dockerfiles/Dockerfile_node9
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/client/node_modules
      ports:
        - "8009:3000"
      command: "npm start"

    ramverk2_node8:
      image: ptorn/bth-ramverk2:node8
    #   build:
    #     context: .
    #     dockerfile: dockerfiles/Dockerfile_node8
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/client/node_modules
      ports:
        - "8008:3000"
      command: "npm start"

    ramverk2_node6:
      image: ptorn/bth-ramverk2:node6
    #   build:
    #     context: .
    #     dockerfile: dockerfiles/Dockerfile_node6
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/client/node_modules
      ports:
        - "8006:3000"
      command: "npm start"

    ramverk2_latest_test:
      build:
        context: .
        dockerfile: dockerfiles/Dockerfile_node_latest
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/client/node_modules
      ports:
        - "3001:3000"
      command: "npm test"

    ramverk2_node9_test:
      build:
        context: .
        dockerfile: dockerfiles/Dockerfile_node9
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/client/node_modules
      ports:
        - "3002:3000"
      command: "npm test"

    ramverk2_node8_test:
      build:
        context: .
        dockerfile: dockerfiles/Dockerfile_node8
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/client/node_modules
      ports:
        - "3003:3000"
      command: "npm test"
